name: Make Version

on:
  workflow_dispatch: { }

permissions:
  contents: read


jobs:
  bump-version:
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.set-release-version.outputs.RELEASE_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0 # fetch all history, commits and tags, lerna scans it to the last tag and looks at commits, we need all of it to determine the next version
      - name: Setup NodeJS
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "24"
          cache: "npm"
      - name: Version
        id: bump-version
        uses: dreamorosi/env-test/.github/actions/version-n-changelog@90cc731523404c236d8cbbcf26630b1bf85fdc18
      - name: Print version
        run: |
          echo "new version ${{ steps.bump-version.outputs.new-version }}"
      - name: Stage changes
        run: git add .
      - name: Create PR
        id: create-pr
        uses: ./.github/actions/create-pr
        with:
          temp_branch_prefix: "ci-bump"
          pull_request_title: "chore(ci): bump version to ${{ steps.bump-version.outputs.new-version }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}

